id: P004385
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1CZ1877
  title: ལས་ཀྱི་མེ་ལོང་གི་གཏམ་རྒྱུད་རྣམ་པར་བཤད་པ
  author: ''
  volumes:
    8088f65a1b2640afa1018c1adb48f3f5:
      image_group_id: I1CZ2107
      title: ''
      volume_number: 1
      total_pages: 388
      base_file: v001.txt
